[package]
name = "touying-ustc"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["DRY <1729361922@qq.com>"]
license = "MIT"
description = "Touying Slide Theme for USTC"
homepage = "https://github.com/semidry/Typst_USTC_CS"
repository = "https://github.com/semidry/Typst_USTC_CS"
keywords = ["touying", "slide", "theme", "ustc", "zhongkeda"]
categories = ["presentation"]
exclude = [".github/", "examples/"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.webp"
